# Customize these two to your needs
LIBDIRS=/home/qcar/l/lib
INCDIRS=/home/qcar/l/include

SOURCES = Parse.ml Eval.ml clp_stubs.c Clp.mli Clp.ml
RESULT = app
CLIBS = z bz2 Clp CoinUtils
CFLAGS = -Wall -O3

-include OCamlMakefile
